# Generated by Django 3.2.4 on 2021-06-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soouce', models.CharField(blank=True, max_length=100, null=True, verbose_name='Source')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Author')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('image', models.CharField(blank=True, max_length=100, null=True, verbose_name='Image')),
                ('content', models.TextField(blank=True, max_length=100, null=True, verbose_name='Content')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link')),
                ('date_published', models.DateField()),
            ],
            options={
                'verbose_name': 'Publication',
            },
        ),
    ]
