# Generated by Django 3.2.4 on 2021-06-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='soouce',
        ),
        migrations.AddField(
            model_name='publication',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.source'),
            preserve_default=False,
        ),
    ]
